const escapeRegExp = (value: string) => value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");

export const STATIC_ASSET_LIKE_EXTENSIONS = [
  "7z",
  "bz2",
  "gz",
  "rar",
  "tar",
  "tgz",
  "xz",
  "zip",
  "aac",
  "flac",
  "m4a",
  "mp3",
  "ogg",
  "opus",
  "wav",
  "csv",
  "json",
  "pdf",
  "txt",
  "xml",
  "yaml",
  "yml",
  "otf",
  "ttf",
  "woff",
  "woff2",
  "apng",
  "avif",
  "bmp",
  "gif",
  "ico",
  "jpeg",
  "jpg",
  "png",
  "svg",
  "tif",
  "tiff",
  "webp",
  "mkv",
  "mov",
  "mp4",
  "webm",
  "css",
  "htm",
  "html",
  "js",
  "map",
] as const;

const IMPORTABLE_STATIC_ASSET_EXTENSION_NAMES = [
  "7z",
  "bz2",
  "gz",
  "rar",
  "tar",
  "tgz",
  "xz",
  "zip",
  "aac",
  "flac",
  "m4a",
  "mp3",
  "ogg",
  "opus",
  "wav",
  "csv",
  "htm",
  "html",
  "pdf",
  "txt",
  "xml",
  "yaml",
  "yml",
  "otf",
  "ttf",
  "woff",
  "woff2",
  "apng",
  "avif",
  "bmp",
  "gif",
  "ico",
  "jpeg",
  "jpg",
  "png",
  "svg",
  "tif",
  "tiff",
  "webp",
  "mkv",
  "mov",
  "mp4",
  "webm",
] as const;

export const IMPORTABLE_STATIC_ASSET_EXTENSIONS = IMPORTABLE_STATIC_ASSET_EXTENSION_NAMES.map(
  (extension) => `.${extension}`,
);

const DIRECT_ROUTE_ASSET_EXTENSION_NAMES = [...STATIC_ASSET_LIKE_EXTENSIONS];

export const DIRECT_ROUTE_ASSET_EXTENSIONS = DIRECT_ROUTE_ASSET_EXTENSION_NAMES.map(
  (extension) => `.${extension}`,
);

const DOWNLOAD_ROUTE_ASSET_EXTENSION_NAMES = [
  "7z",
  "bz2",
  "csv",
  "gz",
  "htm",
  "html",
  "pdf",
  "rar",
  "tar",
  "tgz",
  "txt",
  "xml",
  "xz",
  "yaml",
  "yml",
  "zip",
] as const;

export const DOWNLOAD_ROUTE_ASSET_EXTENSIONS = DOWNLOAD_ROUTE_ASSET_EXTENSION_NAMES.map(
  (extension) => `.${extension}`,
);

const COURSE_ASSET_CONTENT_TYPES: Record<string, string> = {
  ".7z": "application/x-7z-compressed",
  ".aac": "audio/aac",
  ".apng": "image/apng",
  ".avif": "image/avif",
  ".bmp": "image/bmp",
  ".bz2": "application/x-bzip2",
  ".css": "text/css; charset=utf-8",
  ".csv": "text/csv; charset=utf-8",
  ".flac": "audio/flac",
  ".gif": "image/gif",
  ".gz": "application/gzip",
  ".htm": "text/html; charset=utf-8",
  ".html": "text/html; charset=utf-8",
  ".ico": "image/x-icon",
  ".jpeg": "image/jpeg",
  ".jpg": "image/jpeg",
  ".js": "text/javascript; charset=utf-8",
  ".json": "application/json; charset=utf-8",
  ".m4a": "audio/mp4",
  ".map": "application/json; charset=utf-8",
  ".mkv": "video/x-matroska",
  ".mov": "video/quicktime",
  ".mp3": "audio/mpeg",
  ".mp4": "video/mp4",
  ".ogg": "audio/ogg",
  ".opus": "audio/ogg; codecs=opus",
  ".otf": "font/otf",
  ".pdf": "application/pdf",
  ".png": "image/png",
  ".rar": "application/vnd.rar",
  ".svg": "image/svg+xml",
  ".tar": "application/x-tar",
  ".tgz": "application/gzip",
  ".tif": "image/tiff",
  ".tiff": "image/tiff",
  ".txt": "text/plain; charset=utf-8",
  ".ttf": "font/ttf",
  ".wav": "audio/wav",
  ".webm": "video/webm",
  ".webp": "image/webp",
  ".woff": "font/woff",
  ".woff2": "font/woff2",
  ".xml": "application/xml; charset=utf-8",
  ".xz": "application/x-xz",
  ".yaml": "application/yaml; charset=utf-8",
  ".yml": "application/yaml; charset=utf-8",
  ".zip": "application/zip",
};

export const STATIC_ASSET_LIKE_EXTENSION_SET = new Set<string>(STATIC_ASSET_LIKE_EXTENSIONS);
export const IMPORTABLE_STATIC_ASSET_EXTENSION_SET = new Set<string>(
  IMPORTABLE_STATIC_ASSET_EXTENSIONS,
);
export const DIRECT_ROUTE_ASSET_EXTENSION_SET = new Set<string>(DIRECT_ROUTE_ASSET_EXTENSIONS);
export const DOWNLOAD_ROUTE_ASSET_EXTENSION_SET = new Set<string>(DOWNLOAD_ROUTE_ASSET_EXTENSIONS);

export const createAssetExtensionRegex = (extensions: readonly string[]) =>
  new RegExp(
    `\\.(${extensions.map((extension) => escapeRegExp(extension.slice(1))).join("|")})$`,
    "i",
  );

export const getCourseAssetContentType = (extension: string) =>
  COURSE_ASSET_CONTENT_TYPES[extension.toLowerCase()] ?? "application/octet-stream";
